### ISSUE TITLE
Java8 HashMap/Map have a putIfAbsent method that conflicts with DynMap

### ISSUE THREAD

**Issue by alextg-github** [trendrr/java-oss-lib#24]
DynMap provides a void putIfAbsent method. In Java8, the Map<K,V> interface has a putIfAbsent method that returns a value of type V. As a result, compiling against DynMap gets errors like:
error: putIfAbsent(java.lang.String,java.lang.Object) in com.trendrr.oss.DynMap cannot implement putIfAbsent(K,V) in java.util.Map

Either the method should be dropped, it should be changed to return v, or it should be renamed.

**Comment by MarkG** [comment]
https://github.com/trendrr/java-oss-lib/pull/25

**Comment by MarkJGrabois** [comment]
#25 has been merged and trendrr-oss uploaded to artifactory
